service: school-reyfow-login
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  login:
    handler: app.lambdaHandler
    events:
      - httpApi:
          path: /login
          method: post
plugins:
  - serverless-plugin-typescript
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
 
